//
// ForecastAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

// MARK: - ForecastAPI

open class ForecastAPI {

  /// Forecast
  ///
  /// - parameter siteId: (query)
  /// - parameter readingParameter: (query)  (optional, default to "00060")
  /// - parameter startDate: (query)  (optional)
  /// - parameter endDate: (query)  (optional)
  /// - returns: [ForecastDataPoint]
  @available(*, deprecated, message: "This operation is deprecated.")
  @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
  open class func forecastForecastGet(
    siteId: String,
    readingParameter: String? = nil,
    startDate: Date? = nil,
    endDate: Date? = nil)
    async throws -> [ForecastDataPoint]
  {
    try await forecastForecastGetWithRequestBuilder(
      siteId: siteId,
      readingParameter: readingParameter,
      startDate: startDate,
      endDate: endDate).execute().body
  }

  /// Forecast
  /// - GET /forecast
  /// - parameter siteId: (query)
  /// - parameter readingParameter: (query)  (optional, default to "00060")
  /// - parameter startDate: (query)  (optional)
  /// - parameter endDate: (query)  (optional)
  /// - returns: RequestBuilder<[ForecastDataPoint]>
  @available(*, deprecated, message: "This operation is deprecated.")
  open class func forecastForecastGetWithRequestBuilder(
    siteId: String,
    readingParameter: String? = nil,
    startDate: Date? = nil,
    endDate: Date? = nil)
    -> RequestBuilder<[ForecastDataPoint]>
  {
    let localVariablePath = "/forecast"
    let localVariableURLString = FlowForecastAPI.basePath + localVariablePath
    let localVariableParameters: [String: Any]? = nil

    var localVariableUrlComponents = URLComponents(string: localVariableURLString)
    localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
      "site_id": (wrappedValue: siteId.encodeToJSON(), isExplode: true),
      "reading_parameter": (wrappedValue: readingParameter?.encodeToJSON(), isExplode: true),
      "start_date": (wrappedValue: startDate?.encodeToJSON(), isExplode: true),
      "end_date": (wrappedValue: endDate?.encodeToJSON(), isExplode: true),
    ])

    let localVariableNillableHeaders: [String: Any?] = [
      :
    ]

    let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

    let localVariableRequestBuilder: RequestBuilder<[ForecastDataPoint]>.Type = FlowForecastAPI.requestBuilderFactory.getBuilder()

    return localVariableRequestBuilder.init(
      method: "GET",
      URLString: (localVariableUrlComponents?.string ?? localVariableURLString),
      parameters: localVariableParameters,
      headers: localVariableHeaderParameters,
      requiresAuthentication: false)
  }
}
