//
// UsgsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

// MARK: - UsgsAPI

open class UsgsAPI {

  /// Forecast
  ///
  /// - parameter uSGSFlowForecastRequest: (body)
  /// - returns: [ForecastDataPoint]
  @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
  open class func forecastUsgsForecastPost(uSGSFlowForecastRequest: USGSFlowForecastRequest) async throws -> [ForecastDataPoint] {
    try await forecastUsgsForecastPostWithRequestBuilder(uSGSFlowForecastRequest: uSGSFlowForecastRequest).execute().body
  }

  /// Forecast
  /// - POST /usgs/forecast
  /// - parameter uSGSFlowForecastRequest: (body)
  /// - returns: RequestBuilder<[ForecastDataPoint]>
  open class func forecastUsgsForecastPostWithRequestBuilder(uSGSFlowForecastRequest: USGSFlowForecastRequest)
    -> RequestBuilder<[ForecastDataPoint]>
  {
    let localVariablePath = "/usgs/forecast"
    let localVariableURLString = FlowForecastAPI.basePath + localVariablePath
    let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: uSGSFlowForecastRequest)

    let localVariableUrlComponents = URLComponents(string: localVariableURLString)

    let localVariableNillableHeaders: [String: Any?] = [
      "Content-Type": "application/json",
    ]

    let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

    let localVariableRequestBuilder: RequestBuilder<[ForecastDataPoint]>.Type = FlowForecastAPI.requestBuilderFactory.getBuilder()

    return localVariableRequestBuilder.init(
      method: "POST",
      URLString: (localVariableUrlComponents?.string ?? localVariableURLString),
      parameters: localVariableParameters,
      headers: localVariableHeaderParameters,
      requiresAuthentication: false)
  }
}
