type_name:
  allowed_symbols: "_"
identifier_name:
  min_length: 2
line_length:
  warning: 220
  error: 250

excluded:
  - .build
  - .swiftpm
  - .git
  - .github
  - .vscode
  - .swiftformat
  - .swiftlint.yml
  - .swiftpackage
  - .swiftpackage.resolved

disabled_rules:
  - trailing_whitespace  # Handled by IDE formatting

# Enables documentation, concurrency, and modern patterns
documentation: warning
strict_concurrency: warning
sendable: warning
implicitly_unwrapped_optional: error