//
// ForecastDataPoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

// MARK: - ForecastDataPoint

public struct ForecastDataPoint: Codable, JSONEncodable, Hashable {

  // MARK: Lifecycle

  public init(index: String, pastValue: Double?, forecast: Double?, lowerErrorBound: Double?, upperErrorBound: Double?) {
    self.index = index
    self.pastValue = pastValue
    self.forecast = forecast
    self.lowerErrorBound = lowerErrorBound
    self.upperErrorBound = upperErrorBound
  }

  // MARK: Public

  public enum CodingKeys: String, CodingKey, CaseIterable {
    case index
    case pastValue = "past_value"
    case forecast
    case lowerErrorBound = "lower_error_bound"
    case upperErrorBound = "upper_error_bound"
  }

  /// The date or index of the data point.
  public var index: String
  public var pastValue: Double?
  public var forecast: Double?
  public var lowerErrorBound: Double?
  public var upperErrorBound: Double?

  // Encodable protocol methods

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(index, forKey: .index)
    try container.encode(pastValue, forKey: .pastValue)
    try container.encode(forecast, forKey: .forecast)
    try container.encode(lowerErrorBound, forKey: .lowerErrorBound)
    try container.encode(upperErrorBound, forKey: .upperErrorBound)
  }
}

