//
// USGSFlowForecastRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

// MARK: - USGSFlowForecastRequest

public struct USGSFlowForecastRequest: Codable, JSONEncodable, Hashable {

  // MARK: Lifecycle

  public init(siteId: String, readingParameter: String, startDate: Date?, endDate: Date?) {
    self.siteId = siteId
    self.readingParameter = readingParameter
    self.startDate = startDate
    self.endDate = endDate
  }

  // MARK: Public

  public enum CodingKeys: String, CodingKey, CaseIterable {
    case siteId = "site_id"
    case readingParameter = "reading_parameter"
    case startDate = "start_date"
    case endDate = "end_date"
  }

  /// The USGS site ID
  public var siteId: String
  /// The USGS reading parameter
  public var readingParameter: String
  public var startDate: Date?
  public var endDate: Date?

  // Encodable protocol methods

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(siteId, forKey: .siteId)
    try container.encode(readingParameter, forKey: .readingParameter)
    try container.encode(startDate, forKey: .startDate)
    try container.encode(endDate, forKey: .endDate)
  }
}

