//
// ValidationError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

// MARK: - ValidationError

public struct ValidationError: Codable, JSONEncodable, Hashable {

  // MARK: Lifecycle

  public init(loc: [ValidationErrorLocInner], msg: String, type: String) {
    self.loc = loc
    self.msg = msg
    self.type = type
  }

  // MARK: Public

  public enum CodingKeys: String, CodingKey, CaseIterable {
    case loc
    case msg
    case type
  }

  public var loc: [ValidationErrorLocInner]
  public var msg: String
  public var type: String

  // Encodable protocol methods

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(loc, forKey: .loc)
    try container.encode(msg, forKey: .msg)
    try container.encode(type, forKey: .type)
  }
}

